- debug:
    msg: "Variable output: {{ hostvars['localhost']['roles_nginx'].stdout }}"

- name: Install nginx
  apt: name=nginx
  become: true
  when: hostvars['localhost']['roles_nginx'].stdout is defined and hostvars['localhost']['roles_nginx'].stdout != ''

- name: Create nginx configs
  template:
    src: "roles/nginx/templates/{{ item }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "default"
    - "board"
    - "blog"
    - "nextcloud"
    - "dav"
    - "sync"
    - "site"
    - "api"
    - "bank"
    - "transmission"
  become: true
  when: hostvars['localhost']['roles_nginx'].stdout is defined and hostvars['localhost']['roles_nginx'].stdout != ''

- name: Create nginx config addons
  template:
    src: "roles/nginx/templates/conf.d/{{ item }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "log_format_json"
    - "limits"
  become: true
  when: hostvars['localhost']['roles_nginx'].stdout is defined and hostvars['localhost']['roles_nginx'].stdout != ''

- name: Link nginx configs
  file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    state: link
    force: true
  with_items:
    - "default"
    - "blog"
    - "board"
    - "nextcloud"
    - "dav"
    - "sync"
    - "site"
    - "api"
    - "bank"
    - "transmission"
  become: true
  when: hostvars['localhost']['roles_nginx'].stdout is defined and hostvars['localhost']['roles_nginx'].stdout != ''

- name: Check if dhparam.pem exists
  stat:
    path: "/etc/ssl/certs/dhparam.pem"
  register: dhparam

- name: Issue dhparam.pem
  command: "/usr/bin/openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"
  become: true
  when: dhparam.stat.exists == False

- name: Test nginx configs
  command: /usr/sbin/nginx -t
  become: true
  when: hostvars['localhost']['roles_nginx'].stdout is defined and hostvars['localhost']['roles_nginx'].stdout != ''

- name: Reload nginx 
  command: /bin/systemctl reload nginx.service
  become: true
  when: hostvars['localhost']['roles_nginx'].stdout is defined and hostvars['localhost']['roles_nginx'].stdout != ''
