- name: Datasources directory
  file:
    path: /etc/datasources
    state: directory
    mode: 0755
  become: true

- name: Api secrets
  template:
    src: "roles/secrets/templates/apps-api.json.j2"
    dest: "/etc/datasources/apps-api.json"
    owner: apps
    group: apps
    mode: 0400
  become: true

- name: IFTTT Maker token
  template:
    src: "roles/secrets/templates/ifttt-token.j2"
    dest: "/etc/datasources/ifttt-token"
    owner: apps
    group: apps
    mode: 0400
  become: true
