- name: Datasources directory
  file:
    path: /etc/datasources
    state: directory
    mode: 0755
  become: true

- name: Apps user
  user:
    name: apps
    shell: /bin/bash

- name: Api secrets
  template:
    src: "roles/secrets/templates/apps-api.json.j2"
    dest: "/etc/datasources/apps-api.json"
    owner: apps
    group: apps
    mode: 0400
  become: true
  diff: false

- name: Cloudflare secrets
  template:
    src: "roles/secrets/templates/cloudflare.ini.j2"
    dest: "/etc/datasources/cloudflare.ini"
    owner: root
    group: root
    mode: 0400
  become: true
  diff: false

- name: IFTTT Maker token
  template:
    src: "roles/secrets/templates/ifttt-token.j2"
    dest: "/etc/datasources/ifttt-token"
    owner: apps
    group: apps
    mode: 0400
  become: true
  diff: false

- name: Check if rcmd.space certificate exists
  stat:
    path: "/etc/letsencrypt/archive/rcmd.space/fullchain1.pem"
  register: rcmd_cert

- name: Check if it-the-drote.tk certificate exists
  stat:
    path: "/etc/letsencrypt/archive/it-the-drote.tk/fullchain1.pem"
  register: itd_cert

- name: Issue wildcard certificates rcmd.space
  command: "/usr/bin/certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/datasources/cloudflare.ini -d rcmd.space,*.rcmd.space --preferred-challenges dns-01 -m azer.abdullaev@protonmail.ch --agree-tos --no-eff-email"
  become: true
  when: rcmd_cert.stat.exists == False

- name: Issue wildcard certificates it-the-drote.tk
  command: "/usr/bin/certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/datasources/cloudflare.ini -d it-the-drote.tk,*.it-the-drote.tk --preferred-challenges dns-01 -m azer.abdullaev@protonmail.ch --agree-tos --no-eff-email"
  become: true
  when: itd_cert.stat.exists == False