- name: Datasources directory
  file:
    path: /etc/datasources
    state: directory
    mode: 0755

- name: Api secrets
  template:
    src: "{{ ansible_env.PWD }}/roles/secrets/templates/apps-api.json.j2"
    dest: "/etc/datasources/apps-api.json"
    owner: apps
    group: apps
    mode: 0400