- name: Collecting Facts
  hosts: staging
  gather_facts: yes

- name: Set up local development environment
  vars_files:
    - private/secrets.yml
  hosts: staging
  roles:
    - earlystageconfigs
    - firewall
    - debrepos
    - users
    - services
    - secrets
