- name: Collecting Facts
  hosts: production
  gather_facts: yes

- name: Set up local development environment
  vars_files:
    - "{{ ansible_env.HOME }}/.ansible/vault.yml"
  hosts: production
  roles:
    - earlystageconfigs
    - firewall
    - secrets
    - debrepos
    - users
    - services
