- name: Reload iptables
  command: sh -c "iptables --flush INPUT; cat /etc/firewall/iptables-input | bash"
  become: true
- name: Reload ip6tables
  command: sh -c "ip6tables --flush INPUT; cat /etc/firewall/ip6tables-input | bash"
  become: true
