- include: debian.yml
  when: ansible_os_family == "Debian"

- include: osx.yml
  when: ansible_os_family == "Darwin"

- name: Install essential Node.js packages
  npm:
    name: {{ item }}
    global: yes
    state: present
  with_items:
    - pug
    - marked
  become: true
