- include: debian.yml
  when: ansible_os_family == "Debian"

- stat: "path={{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_directory

- name: Install oh-my-zsh
  command: "git clone git://github.com/robbyrussell/oh-my-zsh.git {{ ansible_env.HOME }}/.oh-my-zsh"
  ignore_errors: yes

- name: Change shell to zsh
  command: "chsh -s /bin/zsh {{ ansible_env.LOGNAME }}"
  become: true

- name: Install zshrc
  template:
    src: "roles/zsh/templates/zshrc.j2"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: '0644'
  become: true
