- stat: "path={{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_directory

- name: Install oh-my-zsh
  command: "git clone git://github.com/robbyrussell/oh-my-zsh.git {{ ansible_env.HOME }}/.oh-my-zsh"
  when: ohmyzsh_directory.stat.exists == False

- name: Change shell to zsh
  command: "chsh -s /bin/zsh {{ ansible_env.LOGNAME }}"
  sudo: yes

- name: Install zshrc
  template:
    src: "{{ ansible_env.PWD }}/roles/zsh/templates/zshrc.j2"
    dest: "{{ ansible_env.HOME }}/.zsh"
    mode: '0644'
