- name: Install development tools for Debian
  apt: name={{ item }} state=installed
  with_items:
    - apt-transport-https
    - gnupg-curl
    - devscripts
    - dh-make
    - dupload
    - ruby-ronn
    - lxc
  become: true
