- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Disable bash history
  file:
    src: "/dev/null"
    dest: "/root/.bash_history"
    state: link
    force: true
  become: true

- name: Disable zsh history
  file:
    src: "/dev/null"
    dest: "/root/.zsh_history"
    state: link
    force: true
  become: true

- name: Force user-defined configs for apt
  template:
    src: "roles/earlystageconfigs/templates/forceuserdefinedconfigs.j2"
    dest: "/etc/apt/apt.conf.d/forceuserdefinedconfigs"
    owner: root
    group: root
    mode: 0644
  become: true

- stat: "path=/root/.ssh/id_rsa"
  register: sshkey

- name: Generate ssh key for root user
  command: "ssh-keygen -t rsa -N '' -f /root/.ssh/id_rsa"
  when: sshkey.stat.exists == False
  become: true

- name: Copy the public key
  command: "cat /root/.ssh/id_rsa.pub"
  register: pubkey

- name: Prompt the operator to copy the public key
  pause:
    prompt: "Please copy the following key and then add it to the private repository user \n\n{{ pubkey.stdout }}\n\nAfter copying the key, press [Enter]"
