- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Disable bash history
  file:
    src: "/dev/null"
    dest: "/root/.bash_history"
    state: link
    force: true
  become: true

- name: Disable zsh history
  file:
    src: "/dev/null"
    dest: "/root/.zsh_history"
    state: link
    force: true
  become: true

- name: Force user-defined configs for apt
  template:
    src: "roles/earlystageconfigs/templates/forceuserdefinedconfigs.j2"
    dest: "/etc/apt/apt.conf.d/forceuserdefinedconfigs"
    owner: root
    group: root
    mode: 0644
  become: true
