- include: debian.yml
  when: ansible_os_family == "Debian"

- name: Install screenrc
  template:
    src: "roles/screen/templates/screenrc.j2"
    dest: "{{ ansible_env.HOME }}/.screenrc"
    mode: '0644'
