- name: Setup gpg keys
  command: "apt-key adv --fetch-keys --no-tty {{ item.value.repo_gpg }}"
  become: true
  with_dict: "{{ repositories }}"

- name: Setup additional repositories
  template:
    src: "roles/debrepos/templates/repo.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item.key }}.list"
  with_dict: "{{ repositories }}"
  become: true

- name: Update apt cache
  apt:
    update_cache: true
  become: true
  ignore_errors: true
