- name: Install OpenVPN
  apt: name={{ item }}
  with_items:
    - "openvpn"
    - "easy-rsa"
  become: true

- stat: "path=/etc/openvpn/easy-rsa"
  register: easyrsa

- name: Copy easy-rsa scripts
  command: cp -r /usr/share/easy-rsa/ /etc/openvpn
  when: easyrsa.stat.exists == False
  become: true

- name: Install warpzone config
  template:
    src: "roles/openvpn/templates/warpzone.conf.j2"
    dest: "/etc/openvpn/warpzone.conf"
    owner: root
    group: root
    mode: 0644
  become: true

- name: OpenVPN keys directory
  file:
    path: /etc/openvpn/easy-rsa/keys
    state: directory
    mode: 0700
  become: true

- stat: "path=/etc/openvpn/dh2048.pem"
  register: dhparam

- name: Generate Diffie-Helman parameters
  command: openssl dhparam -out /etc/openvpn/dh2048.pem 2048
  when: dhparam.stat.exists == False
  become: true

#- name: Erase server keys
#  command: chdir=/etc/openvpn/easy-rsa /etc/openvpn/easy-rsa/clean-all
#  become: true
#
#- name: Generate CA keys
#  command: chdir=/etc/openvpn/easy-rsa /etc/openvpn/easy-rsa/build-ca
#  become: true
#
#- name: Generate server keys
#  command: chdir=/etc/openvpn/easy-rsa /etc/openvpn/easy-rsa/build-key-server server
#  become: true
